### ISSUE TITLE
Screenshots in add-on listings should be localizable

### ISSUE THREAD

**Issue by jikamens** [thundernest/addons-server#102]
I should be able to have different screenshots for different languages in my add-on listing. My screenshots all show localized strings and the users looking at screenshots should see the strings in their language.

**Comment by Sancus** [comment]
AMO doesn't even support this, afaik, so the chance we ever add this is so negligible I'm not even sure it's honest to leave this open.

**Comment by jikamens** [comment]
If I file an issue about it upstream for AMO and they fix it, will that fix eventually make its way into ATN? If so, where do AMO issues get field nowadays?

**Comment by ovari** [comment]
Image _captions_ can be localized. Would be nice if the images could be localized too.

**Comment by Sancus** [comment]
> If I file an issue about it upstream for AMO and they fix it, will that fix eventually make its way into ATN? If so, where do AMO issues get field nowadays?

No promises, but it would substantially increase the likelihood of it eventually arriving, yes. We're quite far behind relative to AMO because they've made a lot of incompatible changes. But even a patch on their version would be easier to backport than developing it myself.

Please note that ATN is NOT under active development. I do critical bug fixes and features that are necessary for basic functionality to continue working. I say "no" to all non-critical feature requests as a rule. The reason for that is that we do not have a dedicated webdev nor a designer, so any dev time on this site has to be fit into no more than 30-40% of my overall time. And as we add more services, the amount of time I have to spend on webdev on any particular site continues to decrease.

This feature would:
- Be used by few developers
- Require new UI design/coding
- Require database and file storage changes that would be incompatible with upstream addons-server

There are a lot of web-facing things that need improvement before I worry about trying to add features like this to ATN. For example, the in-client Discovery Pane needs a complete redesign and rewrite, and that's something that millions of users see every week. So does the core thunderbird.net website, and we're working on that too. The list of things is long, and 1 full time person only goes so far.

In any case, [the upstream AMO repo is here](https://github.com/mozilla/addons-server).

**Comment by jikamens** [comment]
Somebody beat me to it: https://github.com/mozilla/addons-server/issues/5662. Two years ago.
Closing here, no reason to keep open if it's that unlikely to ever be implemented. *sigh*
