### ISSUE TITLE
UIL addon licence not working

### ISSUE THREAD

**Issue by lisabiziou** [thundernest/addons-server#116]
hallo

In my thunderbird i got a message saying my licence for UIL was expiring.  First i checked out wat this is , i didnt even know i needed a licence. I went to click on the button to buy a licence but nothing happened.

I want to buy the licence but cant. I realise its a bug and ask if it can be checked out and repaired

![uil](https://user-images.githubusercontent.com/26070926/67763054-18f76800-fa47-11e9-8d99-97a044b4c444.png)

lisa

**Comment by kewisch** [comment]
Hi Lisa, is this a problem with a specific add-on? Thunderbird itself doesn't require a license and is free to use. If this is about a specific add-on you depend on, please contact the author instead.

I'm closing this since the issue tracker is meant for technical issues related to addons.thunderbird.net, but happy to discuss further if this is a Thunderbird issue.
