### ISSUE TITLE
Search for 'Spellcheck' first leads to 'Language Packs' (German/Deutsch: Suche nach 'Rechtschreibung' führt zuerst zu 'Sprachpaket')

### ISSUE THREAD

**Issue by dvschuetz** [thundernest/addons-server#135]
Dear Thunderbird-Team,

if a german-speaking user, using the German localization of Thunderbird already(!), wants to activate the spellchecker in Thunderbird, he can do that in menu Extras/Einstellungen/Verfassen/Rechtschreibung, see screenshot 1. 
There is a link "Weitere Wörterbücher herunterladen" (meaning: "download more dictionaries").
Klicking on this link, the **first** option in the new window is: "In Ihrer Sprache verfügbar: German - Deutsch - Sprachpaket herunterladen" (meaning: "download language pack") - see screenshot 2.

That is **confusing**, as you can read in many users' comments (see screenshot 3). Only if he scrolls down underneath "Alle Sprachen" (All Languages), he will be able to find the needed spell check dictionary.
Of course I noticed the explaining text above - but I guess not everyone reads it. The default user expects after klicking on "dictionary" to find dictionaries, and nothing else.
Even more: the title of the page is "Wörterbücher & Sprachpakete" (dictionaries and language packs) - and not the other way round, i.e. "language packs" first and then, second, "dictionaries".

My suggestions: 
- change the linked AddOns-Website to show dictionaries as the _uppermost_ option, or:
- change the linked AddOns-Website to show _only_ dictionaries. (That might require to put another link in Thunderbird code for language packs, I don't know that)

Thank you for all your efforts!
Dietmar

Screenshot 1:  Thunderbird options
![grafik](https://user-images.githubusercontent.com/5382362/81601808-c7ec0780-93cb-11ea-850e-06db96a2484f.png)

Screenshot 2: AddOns Page
![grafik](https://user-images.githubusercontent.com/5382362/81602075-421c8c00-93cc-11ea-984f-c58b7419661f.png)

Screenshot 3: confused users' comments on AddOns Page
![grafik](https://user-images.githubusercontent.com/5382362/81603723-1c44b680-93cf-11ea-8f5e-4fb780efb39a.png)

**Comment by Sancus** [comment]
For most languages, the first line on the page contains a dictionary under "Wörterbüch" in addition to a language pack, see English: https://addons.thunderbird.net/en-US/thunderbird/language-tools/

But because there are multiple variations of German, there was no actual dictionary for "de", only "de-DE", etc. The easiest way to solve this is to [move this one](https://addons.thunderbird.net/de/thunderbird/addon/german-dictionary/) to being the default for "de". There are still the other variations below for those who want them.

I agree this UI isn't great, but making significant modifications to ATN UI is not going to happen anytime soon. Long term we will be rebuilding at least the public facing parts of the site UI and things like this could be improved.
