### ISSUE TITLE
TB Add-ons Split from AMO Broke AMO Features within Thunderbird

### ISSUE THREAD

**Issue by Ngamer01** [thundernest/addons-server#14]
Back when Thunderbird had their add-ons site split onto a new site, this had a side-effect of breaking all AMO features within Thunderbird (I'm using TB 60 beta 10).   No add-ons can be updated automatically, add-ons can’t be searched within Thunderbird (but can be in Firefox/an internet browser as a workaround), nor light themes can be installed in Thunderbird from what I can gather with testing.

Extensions can be manually downloaded from Firefox/an internet browser, but can be manually installed in Thunderbird.  Extensions have a work-around.  Light themes have no work-around since you can't download them in Firefox/another internet browser to install in Thunderbird.

Anyways it was suggested for me to open a bug here from this page:
https://blog.mozilla.org/addons/2018/07/17/the-new-thunderbird-add-ons-site-is-now-live/

**Comment by Sancus** [comment]
OK this is a dump of a lot of different issues, most of which I can't reproduce, or have been fixed for TB60 ESR.

1. Add-on update seems to work. I downloaded Cardbook 30.3, and both 'Check for Updates' and setting extensions.update.interval to 60(so I don't have to wait a day for update to trigger..) and then restarting correctly trigger an update and a message in the Add-on Manager that Cardbook will be updated on next restart.

2. I don't know what you mean by "addons cant be searched within Thunderbird". If I go to the Add-on Manager and click in the top right search box and then type "compact" it indeed brings up CompactHeader on ATN. Clicking "Add to Thunderbird" works fine for me in 60.0b10.

3. Light Themes can be installed from the Add-on Manager, click on "Themes" on the left side and then "Choose from thousands of themes." This will bring up ATN and each theme has an "Add" button just below it on mouseover. This works fine in 60.0b10.

There are a number of issues with links in the Add-on Manager opening in your browser instead of staying with Thunderbird, these are known and have been fixed for TB60 ESR. See [Bug 1474382](https://bugzilla.mozilla.org/show_bug.cgi?id=1474382) etc.

**Comment by Ngamer01** [comment]
1) I guess I might have been premature with this.  The add-ons I have installed are very infrequently updated so basically nothing can update if there are no new updates submitted by their authors.  So I can't verify one way or another if this really was nothing at all or if there might be something.

2) Apparently I had to reset some about:config values and now I can search for extensions within Thunderbird.  I might have gummed up the "Get Add-ons" section within TB with the about:config changes though (guess I need to make a new profile to see if that fixes "Get Add-ons").  I might have uncovered something else after resetting my about:config prefs -- I can't use the search bar in the Add-Ons Manager to look for lightweight themes.

3) Yeah when I reset some about:config preferences, I can confirm this is working again.

And good to hear certain links within the Add-on Manager will be fixed for the next main TB beta (since 60 ESR is getting the fixes).

**Comment by Sancus** [comment]
> I can't use the search bar in the Add-Ons Manager to look for lightweight themes.
This is just the way the Add-ons Manager works, which is logic we inherit from Firefox. We could maybe alter the way this works in Thunderbird, I'm not sure, but this isn't really a site bug, and it's not a regression -- it always worked this way. I opened [Bug 1480174.](https://bugzilla.mozilla.org/show_bug.cgi?id=1480174)

For the rest, it would be helpful in the future if you [use a new profile](https://support.mozilla.org/en-US/kb/using-multiple-profiles) especially if you are making about:config changes, and post detailed steps to reproduce for each bug.
