### ISSUE TITLE
Can't add new themes to Thunderbird

### ISSUE THREAD

**Issue by ddotyjr** [thundernest/addons-server#19]
I attempted to add several new themes to Thunderbird but after clicking "Add to Thunderbird" button I only got a page that said it couldn't find what I was looking for. An example is the Mesa Boogie theme at https://addons.thunderbird.net/en-US/thunderbird/addon/mesa-engineering/. The page displayed when I tried to add was https://addons.thunderbird.net/en-US/thunderbird/addon/10900/. All themes seem to have this error.

**Comment by kewisch** [comment]
Can confirm. @Sancus any idea what is going on here?

**Comment by Sancus** [comment]
You can't add lightweight themes to Thunderbird via Firefox or any other browser, you have to add them via the Addons Manager in Thunderbird itself.

This used to link to the Personas Plus addon, but it was deleted by the Firefox addons purge because it doesn't support Thunderbird and hasn't since last year. 

Probably the best thing we can do here is add a rewrite to a support page explaining this.

**Comment by ddotyjr** [comment]
When I access Tools|Add-ons from within Thunderbird (v52.9.1), all attempts to pick a theme open a browser window with the details. You can't add directly from the Add-on page. Is there a way to get the theme files (*.jar) directly?

**Comment by Sancus** [comment]
I don't have TB52 installed and theme installation issues in TB52 aren't really supported, a number of things are broken in it and fixed in TB60.

In Thunderbird 60:
1. Open Add-ons Manager (Tools -> Add-ons)
2. Click Themes on the left side.
3. Click "Choose from thousands of themes." at the top.
4. Click the little grey "Add" button below the theme you want to install. If the theme is not displayed, search for it using the search box in the top right and then click the little grey "Add" button.

Detail panes and a number of other links in this tab will open in the browser unfortunately, but that shouldn't prevent installation. I'm going to file a Thunderbird bug about this though.

The one website bug in all of this is that the "Add" buttons in Thunderbird should be green, not grey.

**Comment by PRDormer** [comment]
When I try this in TB60, I don't see the add button.  If I click on the theme (or try and select themes from the list at the left) it opens a browser window and attempting to add the theme from there doesn't work.

**Comment by PRDormer** [comment]
Ah, I see the add button if I hover the cursor over the theme.  Still, this does mean you can only install the themes shown on this page.  If you select from the list down the side or search for a theme, it opens in a browser and you can't seem to install the theme from the browser.

**Comment by Sancus** [comment]
If you search on the page after clicking "choose from thousands of themes" the search list is in Thunderbird and you can add the themes via mouseover and the Add button. Just don't click on them directly, because that opens in the browser, which is https://bugzilla.mozilla.org/show_bug.cgi?id=1482342

**Comment by Sancus** [comment]
https://addons.thunderbird.net/en-US/thunderbird/addon/10900/ now redirects to https://support.mozilla.org/en-US/kb/install-themes-change-look-thunderbird
