### ISSUE TITLE
Using Google Calender - AddOn not available

### ISSUE THREAD

**Issue by kaischwarze** [thundernest/addons-server#221]
I tried to use Google Calender with teh Extension Provider für Google Kalender (https://addons.thunderbird.net/de/thunderbird/addon/provider-for-google-calendar/) but i do not find it with the AddOn search.

I could download ist from teh origin website, bu dont know how to manage the  installation from my harddisk into Thunderbird

Con you give me a hint, how to get the AddOn into T-Bird . ore en otehr solution for using Google calender in T-Bird

**Comment by MelissaAutumn** [comment]
Hey there! 

Generally when add-ons aren't showing up through the "Find more add-ons" section of Thunderbird it's because the add-on does not support your currently installed version of Thunderbird. This add-on seems to only be compatiable with the release version of Thunderbird, so if you're in beta or daily it won't work until the author updates it. 

If you're unsure what version of Thunderbird you have, you can follow the steps here to find out: https://support.mozilla.org/kb/find-what-version-thunderbird-you-are-using

If you want to try to install it manually, you can follow the instructions here: 
https://support.mozilla.org/kb/installing-addon-thunderbird#w_a-slightly-less-ideal-case-install-from-a-downloaded-xpi-file 

If you still need help downloading or installing this add-on you can try asking a question on our support site, which is located here: 
https://support.mozilla.org/questions/new/thunderbird

Cheers,
Mel
