### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ishida1234** [thundernest/addons-server#41]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
??

**Comment by ishida1234** [comment]
We're sorry, but we can't find what you're looking for.
The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

If you typed in the address, please double check the spelling.
If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.
Or you can just jump over to some of the popular pages on our website.

Are you interested in a list of featured add-ons?
Do you want to search for add-ons? You may go to the search page or just use the search field above.
If you prefer to start over, just go to the add-ons front page.

**Comment by ishida1234** [comment]
why??

**Comment by Sancus** [comment]
Themes cannot be installed via the website and a browser, they must be installed within Thunderbird itself. This requires TB60 or later since the addons site move. See: https://support.mozilla.org/en-US/kb/install-themes-change-look-thunderbird for instructions. If you have further difficulty, please feel free to ask a question on our support forum here: https://support.mozilla.org/en-US/questions/new/thunderbird
