### ISSUE TITLE
running foxes

### ISSUE THREAD

**Issue by 50616** [thundernest/addons-server#43]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
Themes cannot be installed via the website and a browser, they must be installed within Thunderbird itself. This requires TB60 or later since the addons site move. See: https://support.mozilla.org/en-US/kb/install-themes-change-look-thunderbird for instructions. If you have further difficulty, please feel free to ask a question on our support forum here: https://support.mozilla.org/en-US/questions/new/thunderbird
