### ISSUE TITLE
Theme Add to Thunderbird

### ISSUE THREAD

**Issue by sotaventoUY** [thundernest/addons-server#44]
I want to add new themes to thunderbird from https://addons.thunderbird.net/es/thunderbird/, when a I select one and click con "add to thunderbird" button, a page is opened with the following message: "We're sorry, but we can't find what you're looking for."  It happens with all the themes.

![image](https://user-images.githubusercontent.com/39745023/46816649-d4bdfa80-cd53-11e8-94e3-41e9e3f74dc2.png)

![image](https://user-images.githubusercontent.com/39745023/46816729-f8814080-cd53-11e8-9e73-c7313f97a322.png)

**Comment by Sancus** [comment]
Themes cannot be installed via the website and a browser, they must be installed within Thunderbird itself. This requires TB60 or later since the addons site move. See: https://support.mozilla.org/en-US/kb/install-themes-change-look-thunderbird for instructions. If you have further difficulty, please feel free to ask a question on our support forum here: https://support.mozilla.org/en-US/questions/new/thunderbird

The link above that was a 404 now redirects to the instructions page on support.mozilla.org
