### ISSUE TITLE
Set up email export to Mailchimp for mass developer emails

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#6]
We need some kind of export for mass mailing. Mozilla uses basket/exact target, but we don't have that service, so it's probably possible to set up a script with similar functionality for Mailchimp.

**Comment by ovari** [comment]
Is the [MailChimp "Forever Free"](https://mailchimp.com/pricing/) version used by Thunderbird?

Could the Thunderbird [Mail Merge add-on](https://addons.thunderbird.net/thunderbird/addon/mail-merge/) be used instead?

If there are any features missing from the [Mail Merge add-on](https://addons.thunderbird.net/thunderbird/addon/mail-merge/), they could be incorporated so that Thunderbird becomes a better email tool.

Thank you

**Comment by Sancus** [comment]
This was fixed some time ago with an internal script.
