### ISSUE TITLE
Ensure WebExtension Dictionaries work well on ATN

### ISSUE THREAD

**Issue by kewisch** [thundernest/addons-server#66]
Dictionaries are now WebExtensions, and some of the migration code may have landed after the last time the code was imported from AMO. https://github.com/mozilla/addons-server/issues/9522 .

It looks to me like https://reviewers.addons.thunderbird.net/en-us/reviewers/review/spanish-mexico-dictionary is a dictionary, but if you look at the admin view it has addontype_id = 1 (extension) while it should be 3.

In addition, `target_locale` needs to be set correctly. Supposedly once the add-on is uploaded as a dictionary, it will automatically show up on the language tools page.

**Comment by kewisch** [comment]
https://github.com/mozilla/addons-server/blob/4476bc4e2a2d45d469aac2204bb5d8ace04d6bee/src/olympia/files/utils.py#L414-L421 is where WebExtensions get their dictionary status.

**Comment by Sancus** [comment]
We can't update to any version past ~Sept 17th and it looks like this has patches in October, so we'll have to backport I guess.

**Comment by kewisch** [comment]
Might be worth looking through the issues at https://github.com/orgs/mozilla/projects/24

**Comment by ThunderbirdMailDE** [comment]
Unlike AMO, the web extension dictionaries should be downloadable from ATN with any browser. On AMO, this is an annoying obstacle that we should avoid for Thunderbird users on ATN.

**Comment by mkmelin** [comment]
> Might be worth looking through the issues at https://github.com/orgs/mozilla/projects/24

Yep, this looks like something we want do port sooner rather than later. Hopefully not too much conflicts, as this was not a very long time past Sept 17.

**Comment by Sancus** [comment]
These are supported now. In addition, I have migrated all the dictionaries that it is possible to migrate. There are some that cannot be migrated, and the full list is below.

Aside from the first one, the others all have locales that can't be guessed from the filenames etc, the first one has a .dat file instead of a .dic file, and hasn't been touched by the author in at least 8 years('typefix' files were some other automated process).

https://addons.thunderbird.net/en-US/thunderbird/addon/7583 xpi has no .dic file.

https://addons.thunderbird.net/en-US/thunderbird/addon/3075
https://addons.thunderbird.net/en-US/thunderbird/addon/3627
https://addons.thunderbird.net/en-US/thunderbird/addon/3737
https://addons.thunderbird.net/en-US/thunderbird/addon/6526
https://addons.thunderbird.net/en-US/thunderbird/addon/10097
https://addons.thunderbird.net/en-US/thunderbird/addon/10098
https://addons.thunderbird.net/en-US/thunderbird/addon/10186
https://addons.thunderbird.net/en-US/thunderbird/addon/12109
https://addons.thunderbird.net/en-US/thunderbird/addon/12115
https://addons.thunderbird.net/en-US/thunderbird/addon/13375
https://addons.thunderbird.net/en-US/thunderbird/addon/14049
https://addons.thunderbird.net/en-US/thunderbird/addon/14403
https://addons.thunderbird.net/en-US/thunderbird/addon/52184
https://addons.thunderbird.net/en-US/thunderbird/addon/138991
https://addons.thunderbird.net/en-US/thunderbird/addon/181931
https://addons.thunderbird.net/en-US/thunderbird/addon/197684
https://addons.thunderbird.net/en-US/thunderbird/addon/200746
https://addons.thunderbird.net/en-US/thunderbird/addon/200749
https://addons.thunderbird.net/en-US/thunderbird/addon/200750
https://addons.thunderbird.net/en-US/thunderbird/addon/280813
https://addons.thunderbird.net/en-US/thunderbird/addon/299091
https://addons.thunderbird.net/en-US/thunderbird/addon/299093
https://addons.thunderbird.net/en-US/thunderbird/addon/311004
https://addons.thunderbird.net/en-US/thunderbird/addon/328697
https://addons.thunderbird.net/en-US/thunderbird/addon/335791
https://addons.thunderbird.net/en-US/thunderbird/addon/337188
https://addons.thunderbird.net/en-US/thunderbird/addon/344833
https://addons.thunderbird.net/en-US/thunderbird/addon/362677
https://addons.thunderbird.net/en-US/thunderbird/addon/363773
https://addons.thunderbird.net/en-US/thunderbird/addon/363775
https://addons.thunderbird.net/en-US/thunderbird/addon/378684
https://addons.thunderbird.net/en-US/thunderbird/addon/379313
https://addons.thunderbird.net/en-US/thunderbird/addon/381579
https://addons.thunderbird.net/en-US/thunderbird/addon/403358
https://addons.thunderbird.net/en-US/thunderbird/addon/413672
https://addons.thunderbird.net/en-US/thunderbird/addon/417292
https://addons.thunderbird.net/en-US/thunderbird/addon/418776
https://addons.thunderbird.net/en-US/thunderbird/addon/418794
https://addons.thunderbird.net/en-US/thunderbird/addon/421570
https://addons.thunderbird.net/en-US/thunderbird/addon/423006
https://addons.thunderbird.net/en-US/thunderbird/addon/438654
https://addons.thunderbird.net/en-US/thunderbird/addon/444420
https://addons.thunderbird.net/en-US/thunderbird/addon/448340
https://addons.thunderbird.net/en-US/thunderbird/addon/451024
https://addons.thunderbird.net/en-US/thunderbird/addon/459715
https://addons.thunderbird.net/en-US/thunderbird/addon/468003
https://addons.thunderbird.net/en-US/thunderbird/addon/475034
https://addons.thunderbird.net/en-US/thunderbird/addon/479656
https://addons.thunderbird.net/en-US/thunderbird/addon/493974
https://addons.thunderbird.net/en-US/thunderbird/addon/495680
https://addons.thunderbird.net/en-US/thunderbird/addon/514646
https://addons.thunderbird.net/en-US/thunderbird/addon/517664
https://addons.thunderbird.net/en-US/thunderbird/addon/522020
https://addons.thunderbird.net/en-US/thunderbird/addon/528742
https://addons.thunderbird.net/en-US/thunderbird/addon/557564
https://addons.thunderbird.net/en-US/thunderbird/addon/598034
https://addons.thunderbird.net/en-US/thunderbird/addon/643386
https://addons.thunderbird.net/en-US/thunderbird/addon/654968
https://addons.thunderbird.net/en-US/thunderbird/addon/654974
https://addons.thunderbird.net/en-US/thunderbird/addon/654978
https://addons.thunderbird.net/en-US/thunderbird/addon/659430
https://addons.thunderbird.net/en-US/thunderbird/addon/664156
https://addons.thunderbird.net/en-US/thunderbird/addon/691696
https://addons.thunderbird.net/en-US/thunderbird/addon/714676
https://addons.thunderbird.net/en-US/thunderbird/addon/744366
https://addons.thunderbird.net/en-US/thunderbird/addon/781872
https://addons.thunderbird.net/en-US/thunderbird/addon/801004
https://addons.thunderbird.net/en-US/thunderbird/addon/833906
https://addons.thunderbird.net/en-US/thunderbird/addon/842177
https://addons.thunderbird.net/en-US/thunderbird/addon/903565
https://addons.thunderbird.net/en-US/thunderbird/addon/921740

**Comment by Sancus** [comment]
Most of the unmigrated dictionaries have less than 100 users, are abandoned, or both. The exceptions with >100 users are:

https://addons.thunderbird.net/en-US/thunderbird/addon/openmedspel-medical-spellin/
https://addons.thunderbird.net/en-US/thunderbird/addon/nz-english-dictionary/
https://addons.thunderbird.net/en-US/thunderbird/addon/new-zealand-english/
https://addons.thunderbird.net/en-US/thunderbird/addon/au-english-dictionary/
https://addons.thunderbird.net/en-US/thunderbird/addon/spellcheckerlu-dictionary/

**Comment by ThunderbirdMailDE** [comment]
Great to see the webext migration of the dictionaries.

But where can Thunderbird 52 users can now find working dictionaries for this still often used version?

**Comment by Sancus** [comment]
> But where can Thunderbird 52 users find now working dictionaries for this still often used version?

Thunderbird 52 is officially unsupported and less than 3% of users are still using it. You [can still go into the old versions of any dictionary and grab versions before the 'webext' upgrade](https://addons.thunderbird.net/en-US/thunderbird/addon/diccionario-espa%C3%B1ol-m%C3%A9xico/versions/). This is unfortunate, but we can't rewrite the dictionary page to support multiple versions just to make things easier for people who are on unsupported versions. At least there is still a working path, even if it's difficult to use.

**Comment by Sancus** [comment]
I manually upgraded https://addons.thunderbird.net/en-US/thunderbird/addon/openmedspel-medical-spellin/ because it seemed useful.

I'm going to leave the others alone, they are mostly duplicated by more popular options anyway. And this issue is now complete.

**Comment by ThunderbirdMailDE** [comment]
> At least there is still a working path

This path isn't obvious for normal users because of the missing "All / Older Versions" button for dictionaries on ATN / AMO. Users have to type "/versions/" manually at the end of the URL. But okay, only 3 % of users.

**Comment by Sancus** [comment]
> This path isn't obvious for normal users because of the missing "All / Older Versions" button for dictionaries on ATN / AMO.

That link is only missing at the top. If you scroll down to version info at the bottom and open that up, "See complete version history" is there. No need to modify the URL. Anyway, 52 has a number of other issues with add-on installation flow, and hasn't gotten security fixes in some time. There is no point in any approach other than telling 52 users that they need to upgrade.
