### ISSUE TITLE
WebExtension theme uploads are currently not supported

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#67]
### What happened?
Current Thunderbirds support WebExtension themes, however trying to upload a WebExtension theme I get the error: WebExtension theme uploads are currently not supported.
### What did you expect to happen?
WebExtension themes should be supported, probably will be in the future, is there an ETA for that?
It has become a bit more urgent now that uploading of footer images is not possible anymore for Light Weight Themes.
### Anything else we should know?
Light weight version on ATN, without footer: https://addons.thunderbird.net/en-US/thunderbird/addon/numix-blue/
I uploaded the WebExtension version to AMO, and there it works: https://addons.mozilla.org/en-US/firefox/addon/numix-blue/

**Comment by dillenger** [comment]
It is becoming a bit more urgent: since 67b1 and 68a1 Thunderbird only supports WebExtension themes.

**Comment by Sancus** [comment]
OK, I've fixed this and tried static theme upload, it seems to pass validation OK now. So this should work.

There is a migration job that can be run over all old themes to auto-upgrade them, which hasn't been run yet but will be soon, still need to figure that out.

Regardless, this issue should be solved now. Let me know if you have any issues.

**Comment by Sancus** [comment]
OK, this doesn't quite work. I forgot that these things added compatibility information to themes.

I need to apply a patch so that they get Thunderbird compatibility and not Firefox on upload. Will do that tomorrow.

**Comment by Sancus** [comment]
@dillenger You seem to know how these are supposed to work, and I really don't. Any idea why [Dark Fox from AMO](https://addons.mozilla.org/firefox/downloads/file/1219517/dark_fox-1.0-an+fx.xpi) won't install in Thunderbird 60, but your static theme will?

Maybe @darktrojan has some idea too. I'm concerned because I think this is an automatically migrated theme and if we break every single theme for Thunderbird with the migration that would be bad.

**Comment by Sancus** [comment]
OK, after some experimentation, it seems that TB60 requires an applications:{gecko:{}} structure with a GUID and strict_min_version set. This is problematic because, well, LWTs don't have GUIDs. Betas past TB60 don't have this requirement either, the normal migrated static themes from AMO install correctly.

The migration code needs to be altered anyway since it apparently uses [deprecated properties](https://github.com/mozilla/addons-server/issues/10626) that will die on versions 69+.

I guess there is no harm in generating a GUID for each of these in the process.

**Comment by kewisch** [comment]
This could be because we have signing disabled. When addons are signed, their ID is part of the signature. If the addon doesn't have an id in the manifest, then an id is generated. If lwts are also signed, they may get their id from there.

**Comment by Sancus** [comment]
Yep, it's signing. Apparently TB63+ read the signing data even though I thought TB didn't support it...

So. I need to discuss this with Magnus on Monday and see how we actually want to handle this, since as far as I know we can't support signing...

**Comment by Sancus** [comment]
I realize this has been a long time coming, but this is now fixed. Web Extension themes can be uploaded. They also are now listed on the site and show up in search. Please feel free to upload the theme at your leisure.
