### ISSUE TITLE
ATN compatibility overrides broken in TB60.*

### ISSUE THREAD

**Issue by altamira01** [thundernest/addons-server#90]
when I try to install the complement, thunderbird say "could not install gcontactsyn because gcontacsync is not compatible with thunderbird 60.6.1"
gcontactsyn version is 3.0.0
thunderbir version is 60.6.1
Ubuntu 19.04
regards!!!

**Comment by kewisch** [comment]
Please contact the author of the add-on for support.

**Comment by Sancus** [comment]
It turns out that 60.* has subtle bugs in its json update format support. Basically, it ignores the min and max version sent by versioncheck. So, this means if an addon author has used ATN to override the compatibility for an addon version, that override will no longer work.

This addon installs an xpi with max version of "60.0" by using ATN to override it to 60.*, and this override no longer works.

I will need to roll back ATN to using the XML RDF format for versions before 67, since I have no idea when this bug was fixed.

The good news is that beta 67 does seem to respect the versions returned by versioncheck in json format.
