### ISSUE TITLE
Unable to publish a new release of a legacy addon

### ISSUE THREAD

**Issue by holle** [thundernest/addons-server#95]
I have not (yet) converted my addon " Thunderbird Integration für JIRA" into a WebExtension.
It is still an legacy style XUL application and works perfectly.
Now I need to upload a patched version since a user found a bug.
But I am unable to do so since your linter always stops me dead in the tracks complaining ab out this:

>  "/applications/gecko/strict_min_version" should match pattern "^[0-9]{1,3}(\.[a-z0-9]+)+$"
> 
> Error: Your JSON file could not be parsed.
> The "default_locale" is missing localizations.
>
> Error: The "default_locale" value is specified in the manifest, but no matching "messages.json" in the "_locales" directory exists. See: https://mzl.la/2hjcaEE
manifest.json
> We allow and encourage an upgrade but you cannot reverse this process. Once your users have the WebExtension installed, they will not be able to install a legacy add-on.

The URL was: https://addons.thunderbird.net/de/developers/upload/8e4815eacfd8486e96bd43a186188801

Last time I tried to "please" the linter the legacy addon did not even install in my Thunderbird anymore.

Is it possible to exclude XPI files from being checked by the new linter?

I can attach the XPI here if you want to check out the error yourselves.

Thanks in advance,
Holger

**Comment by Sancus** [comment]
Yes, please attach the XPI.

**Comment by holle** [comment]
@Sancus 
Here is the XPI file. Please rename it from .zip to .xpi, since Github only supports ZIP :-)

[createjiraissue-1.0.60.1.zip](https://github.com/thundernest/addons-server/files/3301558/createjiraissue-1.0.60.1.zip)

Thanks,
Holger

**Comment by holle** [comment]
Here is the diff of what changed between 1.0.0.60 and 1.0.60.1 (the previous version should have been 1.0.60.0 already :-) )

[changes.diff.txt](https://github.com/thundernest/addons-server/files/3302092/changes.diff.txt)

**Comment by holle** [comment]
Can I just create "empty" "messages.json" files or if checked, simply  copy the contents from my .properties/.dtd and rearrange them to match the json format?

If I simply copy the en-US into an en folder, will the message about the default locale go away, or shall I set the default locale to en-US instead of en ?

**Comment by Sancus** [comment]
OK I'm confused. You keep talking about this as a legacy add-on. Add-ons with a manifest.json are not legacy addons, even if they have xul overlay stuff in them. The difference between a legacy add-on and a mail extension is the presence of the manifest.json file.

The reason the linter is refusing your upload is that your manifest.json is invalid. [Please see the documentation here](https://developer.thunderbird.net/add-ons/tb68/overlays) on how to properly format your manifest.json -- the correct strict_min_version is "60.0", not "60".

P.S. Trying to cram install.rdf and manifest.json into the same file is unsupported and not recommended. 60 add-ons and 68+ add-ons should be separate. [Please see the note on how to differently version those files](https://developer.thunderbird.net/add-ons/tb68) in the docs.

The linked documentation in the error response seems clear to me on what the source of the locale error is, but I don't really know much about that. If you still can't figure it out after correcting all these other issues, I suggest asking on the [add-ons mailing list](https://thunderbird.topicbox.com/groups/addons) as that's a better place to get support on add-on dev issues.

**Comment by holle** [comment]
@Sancus 

Me too :-)

Last time I tried to upload the 1.0.0.60 version the linter simply refused to accept the XPI since it did *not* contain a manifest.json
Since it is a legacy add-on I could not simply rewire it *but* the upload and publishing worked last time with the install.rdf *and* the manifest.json included in the XPI. Even though it is not supported ...
I will strip the manifest.json from the XPI and reattempt the upload. I will post the results here in a moment.

Thanks in for now,
Holger

**Comment by holle** [comment]
@Sancus 

Removing the manifest.json from the XPI made the upload possible again.
Thanks for your time and effort.

Cheers,
Holger

**Comment by RealRaven2000** [comment]
> P.S. Trying to cram install.rdf and manifest.json into the same file is unsupported and not recommended. 60 add-ons and 68+ add-ons should be separate. [Please see the note on how to differently version those files](https://developer.thunderbird.net/add-ons/tb68) in the docs.

Please do not validate against this (having both files) as long ESR 68 has not been officially released because this is the only valid migration path that allows my users to switch between versions (60 / 68) without creating a one-way street. Having install.rdf and manifest.json work very well as long as the version numbers for both exclude each other - I have paying customers on 3 of my Add-ons and do not want to lose or piss them off. 

It was hard enough to cut off users of Thunderbird 52. Having two separate build processes is painful (I tried) so I want to avoid this until the majority of my Add-on users have safely migrated to Thunderbird 68. In the meantime, I am backporting & publishing for older platforms on Interlink.

**Comment by Sancus** [comment]
> Please do not validate against this (having both files) as long ESR 68 has not been officially released because this is the only valid migration path that allows my users to switch between versions (60 / 68) without creating a one-way street. 

There are no plans to validate against it, so you're fine. I tell people not to do it because that is the official policy. If it causes problems for your add-on we can't help with that. If it doesn't cause problems, you're free to do as you like.

If an add-on has a manifest.json, ATN treats it as a mail extension, so the manifest.json has to be valid and file structure has to follow all the rules for web/mail extensions correctly. The install.rdf is completely ignored by the website.
